### PR TITLE
Changes to the set_change_limit

### PR DESCRIPTION
**Pull request by Akrion**
Seems it requires a body and content type

### CODE REVIEW

**Comment by timdorr** [comment]
This is the case for all of the API endpoints. The query string is just a side effect of Apiary's documentation format.

**Comment by Akrion** [comment]
`The query string is just a side effect of Apiary's documentation format.` Did you see my changes? I added an attribute and removed the `percent={limit_value}` from the URI since it does not belong there. Being there breaks the call and sets 50% always. Now the documentation is correct ... there is 
```{ percent: <VALUE> } ``` as part of the attributres. Just like it was done for the Auth Call which was correct. 

How is this Apiary's documentation format issue?

image

This is the correct call format.

**Comment by timdorr** [comment]
This needs to be applied to every endpoint then. This would be inconsistent, if accepted as-is.

**Comment by Akrion** [comment]
Sure, but that is a separate issue. Lets first agree on the correct format and that this is not Apiary issue and then I have no problem to make the rest consistent with changes to this PR.

The reason I started with this is due to the fact that users ware not being able to make the requests straight from Apiary's documentation page due to the fact the URI was wrong. Getting the Tesla services to work straight from Apiary's page is quite helpful to a good amount of people. Especially now with the 75D uncorking fiasco.

**Pull request closed without merging**
