### PR TITLE
Updates trunk_open to actuate_trunk

### PR DESCRIPTION
**Pull request by jonahwh**
This was a change in the Tesla API sometime around the end of July 2018

### CODE REVIEW

**Comment by timdorr** [comment]
I'm not sure why the test suite passed, but this doesn't appear to be correct. Looking at the cassettes, Tesla's API is saying the command is invalid.

**Comment by jonasman** [comment]
I just tried and this works, version 2018.26

**Comment by jonahwh** [comment]
@timdorr fixed up the tests

**Comment by timdorr** [comment]
Cool, thanks!

**Comment by the-mace** [comment]
Current version on apiary doesn't show this change:
https://timdorr.docs.apiary.io/#reference/vehicle-commands/open-trunkfrunk/open-trunk/frunk

**Pull request merged**
