### PR TITLE
Added refresh_token field in authentication response

### PR DESCRIPTION
**Pull request by jonasman**

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks!

**Comment by jonasman** [comment]
There are other changes in vehicle. I can add them as soon as i have more time

**Comment by dewski** [comment]
What does refresh_token do?

**Comment by timdorr** [comment]
I haven't tested anything with it, but the assumption is it will let you extend or "refresh" the session token without having to enter the auth credentials again. It's a way to support long-lived sessions without having to store users' credentials.

**Pull request merged**
