### PR TITLE
Fixed documentation warning

### PR DESCRIPTION
**Pull request by jonasman**

### CODE REVIEW

**Comment by timdorr** [comment]
[It's normal POST data](https://github.com/timdorr/model-s-api/blob/master/spec/cassettes/client-login.yml#L8), not a JSON blob. This is incorrect.

**Comment by jonasman** [comment]
im using right now a json object to authenticate and it works. Are you sure that that recording is up to date?

**Comment by timdorr** [comment]
That was over a year ago, but the library works fine. They're running a Ruby (maybe Rails, probably Sinatra) app on their end and those tend to be ambivalent about different input formats (I wouldn't be surprised if they accept XML or YAML too). Given that POST is more standardized than JSON, I'd rather leave this as an HTTP standard interface, rather than adding another format layer on top.

**Comment by jonasman** [comment]
Have a look:
Request: POST https://owner-api.teslamotors.com/oauth/token
Request Body:
```
 {
  "grant_type" : "password",
  "client_id" : "e4a9949fcfa04068f59abb5a658f2bac0a3428e4652315490b659d5ab3f35a9e",
  "client_secret" : "c75f14bbadc8bee3a7594412c31416f8300256d7668ea7e6e7f06727bfb9d220",
  "email" : "MY_REAL_EMAIL",
  "password" : "MY_REAL_PASS"
}
```
Result: `{"access_token":"A_TOKEN","token_type":"bearer","expires_in":7776000,"created_at":1457465651}`

**Comment by jonasman** [comment]
Ok. There is only the warnings issue then.

**Comment by timdorr** [comment]
Finally fixed that. They should have been `Attributes`.

**Comment by jonasman** [comment]
Cool :)

**Pull request closed without merging**
